### ISSUE TITLE
Bump dwn-sdk-js to v0.2.2 and remove patch

### ISSUE THREAD

**Issue by shamilovtim** [TBD54566975/web5-wallet#106]
- Latest dwn-sdk-js is out 
- Patch can be removed

**Comment by amika-sq** [comment]
I have the bump in mobile repo on a branch: `amika/bump-dwn`

However, the `@web5/agent` package hasn't been updated yet, which is causing our instantiation of `DwnManager` to not work appropriately: https://github.com/TBD54566975/web5-wallet/blob/main/src/features/identity/IdentityAgentManager.ts#L36

Once the Web5 packages are updated, we should be able to upgrade. I'll work with them to get a PR up!

**Comment by amika-sq** [comment]
Found an oddity in the constructors for the various data stored in the DWN. Made a PR against it here: https://github.com/TBD54566975/dwn-sdk-js/pull/513

**Comment by diehuxx** [comment]
> However, the @web5/agent package hasn't been updated yet

Hi @amika-sq -- I'm working on this today and Monday. Tonight I'll push a branch with my progress, though it may still be WIP at that point.

**Comment by diehuxx** [comment]
@amika-sq she's merged :)

**Comment by amika-sq** [comment]
Perfect! I'll go ahead and make an alpha version of the web5 packages and get it integrated!
