### ISSUE TITLE
Passphrase screens have content covered by keyboard on iOS

### ISSUE THREAD

**Issue by amika-sq** [TBD54566975/web5-wallet#126]
On iOS, the keyboard covers up the action buttons on both the `CreatePassphraseScreen` and `EnterPassphraseScreen`. 

These screens do seem to work properly on Android, so it might be an iOS-only issue with our React Native components?

![IMG_1044](https://github.com/TBD54566975/web5-wallet/assets/88001738/162bfda3-f18f-4311-89fe-50cb2e3a4f0b)

**Comment by csuwildcat** [comment]
@shamilovtim can you sort this bug out?

**Comment by shamilovtim** [comment]
> @shamilovtim can you sort this bug out? 

Yeah I've got a great long term solution / abstraction for this
