### ISSUE TITLE
Create a file-based DataStore for mobile's local DWN

### ISSUE THREAD

**Issue by amika-sq** [TBD54566975/web5-wallet#47]
Currently, DWNs storage in the wallet uses stores that are backed by SQLite. 

As we would like to start storing larger blob data (ex: profile avatars), it would be ideal to store these files directly to disk, instead of inside an SQLite table's blob column.

**Comment by shamilovtim** [comment]
One call out for the fs thing is that I’m pretty sure that’s what react-native-leveldb does (an on disk db) so we could try and use react-native-leveldb under the hood and create a new bespoke adapter for either react-native-leveldb or something like expo-filesystem

**Comment by amika-sq** [comment]
Interesting. `react-native-leveldb` is an on disk db, but so is `sqlite`. I’m not really sure what the differences are, or why one would be preferable to the other, but I guess I can find out!

**Comment by pax-k** [comment]
@amika-sq @shamilovtim I started this [@hyphen-id/rn-async-storage-level](https://www.npmjs.com/package/@hyphen-id/rn-async-storage-level) specifically to solve this problem. Do you have any feedback? I can continue working on it asap, because we also need it.

**Comment by amika-sq** [comment]
Hey @pax-k! I wasn't aware of this project, but I can take a look! 

@shamilovtim and I did chat previously about the possibility of using AsyncStorage, but it sounded like there was some hesitations there. I'm not super familiar with the React Native, but @shamilovtim mentioned that AsyncStorage was an example of a library that a lot of people used but wasn't really good. I haven't worked with at all to have any sort of opinion on it though.

**Comment by shamilovtim** [comment]
I would assume since we're storing binary and AsyncStorage expects to work with only strings it's a non-starter for us @pax-k @amika-sq
